export type WorldCupTeamSeed = {
  code: string;
  name: string;
  flag: string;
  group: string;
};

export const WORLD_CUP_TEAMS: WorldCupTeamSeed[] = [
  { code: "mx", name: "México", flag: "🇲🇽", group: "A" },
  { code: "za", name: "Sudáfrica", flag: "🇿🇦", group: "A" },
  { code: "kr", name: "República de Corea", flag: "🇰🇷", group: "A" },
  { code: "cz", name: "República Checa", flag: "🇨🇿", group: "A" },
  { code: "ca", name: "Canadá", flag: "🇨🇦", group: "B" },
  { code: "ba", name: "Bosnia", flag: "🇧🇦", group: "B" },
  { code: "qa", name: "Catar", flag: "🇶🇦", group: "B" },
  { code: "ch", name: "Suiza", flag: "🇨🇭", group: "B" },
  { code: "br", name: "Brasil", flag: "🇧🇷", group: "C" },
  { code: "ma", name: "Marruecos", flag: "🇲🇦", group: "C" },
  { code: "ht", name: "Haití", flag: "🇭🇹", group: "C" },
  { code: "gb-sct", name: "Escocia", flag: "🏴", group: "C" },
  { code: "us", name: "Estados Unidos", flag: "🇺🇸", group: "D" },
  { code: "py", name: "Paraguay", flag: "🇵🇾", group: "D" },
  { code: "au", name: "Australia", flag: "🇦🇺", group: "D" },
  { code: "tr", name: "Turquía", flag: "🇹🇷", group: "D" },
  { code: "de", name: "Alemania", flag: "🇩🇪", group: "E" },
  { code: "cw", name: "Curazao", flag: "🇨🇼", group: "E" },
  { code: "ci", name: "Costa de Marfil", flag: "🇨🇮", group: "E" },
  { code: "ec", name: "Ecuador", flag: "🇪🇨", group: "E" },
  { code: "nl", name: "Países Bajos", flag: "🇳🇱", group: "F" },
  { code: "jp", name: "Japón", flag: "🇯🇵", group: "F" },
  { code: "se", name: "Suecia", flag: "🇸🇪", group: "F" },
  { code: "tn", name: "Túnez", flag: "🇹🇳", group: "F" },
  { code: "be", name: "Bélgica", flag: "🇧🇪", group: "G" },
  { code: "eg", name: "Egipto", flag: "🇪🇬", group: "G" },
  { code: "ir", name: "Irán", flag: "🇮🇷", group: "G" },
  { code: "nz", name: "Nueva Zelanda", flag: "🇳🇿", group: "G" },
  { code: "es", name: "España", flag: "🇪🇸", group: "H" },
  { code: "cv", name: "Cabo Verde", flag: "🇨🇻", group: "H" },
  { code: "sa", name: "Arabia Saudí", flag: "🇸🇦", group: "H" },
  { code: "uy", name: "Uruguay", flag: "🇺🇾", group: "H" },
  { code: "fr", name: "Francia", flag: "🇫🇷", group: "I" },
  { code: "sn", name: "Senegal", flag: "🇸🇳", group: "I" },
  { code: "iq", name: "Irak", flag: "🇮🇶", group: "I" },
  { code: "no", name: "Noruega", flag: "🇳🇴", group: "I" },
  { code: "ar", name: "Argentina", flag: "🇦🇷", group: "J" },
  { code: "dz", name: "Argelia", flag: "🇩🇿", group: "J" },
  { code: "at", name: "Austria", flag: "🇦🇹", group: "J" },
  { code: "jo", name: "Jordania", flag: "🇯🇴", group: "J" },
  { code: "pt", name: "Portugal", flag: "🇵🇹", group: "K" },
  { code: "cd", name: "RD de Congo", flag: "🇨🇩", group: "K" },
  { code: "uz", name: "Uzbekistán", flag: "🇺🇿", group: "K" },
  { code: "co", name: "Colombia", flag: "🇨🇴", group: "K" },
  { code: "gb", name: "Inglaterra", flag: "🏴", group: "L" },
  { code: "hr", name: "Croacia", flag: "🇭🇷", group: "L" },
  { code: "gh", name: "Ghana", flag: "🇬🇭", group: "L" },
  { code: "pa", name: "Panamá", flag: "🇵🇦", group: "L" },
];